### ISSUE TITLE
[MPLUGIN-1] Maven fails while developing plugin with 1.5 compliant sources

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#406]
**[Jose Gonzalez Gomez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jgonzalez.openinput@gmail.com)** opened **[MPLUGIN-1](https://issues.apache.org/jira/browse/MPLUGIN-1?redirect=false)** and commented

I'm developing a plugin for Maven, and my sources contains 1.5 features, such as use of generics. When I try to install the plugin in my local repository I get the following:

[INFO] Scanning for projects...
[INFO] ----------------------------------------------------------------------------
[INFO] Building Maven Docbook plugin
[INFO]    task-segment: [install]
[INFO] ----------------------------------------------------------------------------
[INFO] [plugin:descriptor]
[INFO] ----------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] syntax error @[129,64] in file:/C:/Documents and Settings/jgonzalez/Mis documentos/proyectos/otros/maven-opendocbook-plugin/src/
main/java/com/openinput/tools/maven/opendocbook/TransformMojo.java
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
com.thoughtworks.qdox.parser.ParseException: syntax error @[129,64] in file:/C:/Documents and Settings/jgonzalez/Mis documentos/proyectos/otros/maven-opendocbook-plugin/src/main/java/com/openinput/tools/maven/opendocbook/TransformMojo.java
at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:504)
at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:610)
at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:488)
at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:296)
at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:312)
at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:308)
at com.thoughtworks.qdox.JavaDocBuilder$1.visitFile(JavaDocBuilder.java:365)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:43)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.scan(DirectoryScanner.java:52)
at com.thoughtworks.qdox.JavaDocBuilder.addSourceTree(JavaDocBuilder.java:362)
at org.apache.maven.tools.plugin.extractor.java.JavaMojoDescriptorExtractor.execute(JavaMojoDescriptorExtractor.java:477)
at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:69)
at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:99)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:399)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:469)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:448)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 5 seconds
[INFO] Finished at: Tue Nov 22 09:54:13 CET 2005
[INFO] Final Memory: 4M/7M
[INFO] ----------------------------------------------------------------------------

The line causing the error contains the following:

private static class FilePathComparator implements Comparator\<String>

So the problem seems to be caused by qdox not being able to parse 1.5 sources.

---

**Issue Links:**
- [MPLUGIN-21](https://issues.apache.org/jira/browse/MPLUGIN-21) Use of Java 5 annotations in Mojos produce error in QDox Parser
 (_**"is duplicated by"**_)
- [MPLUGIN-15](https://issues.apache.org/jira/browse/MPLUGIN-15) Support includes/excludes
 (_**"is depended upon by"**_)

19 votes, 10 watchers

**Comment by jira-importer** [comment]
**[Jimisola Laursen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jimisola)** commented

There doesn't seem to be any activity around this issue. The use of Java 1.5 functionality is being more and more common nowadays. This improvement/bug fix is therefore becoming more and more important. Because of this issue I can't reuse code since most other source I write is in Java 1.5.

Found mvn-anno-mojo (http://sourceforge.net/projects/mvn-anno-mojo) btw: "Maven 2 build system extention that allows writing annotatd Mojos using JDK 1.5 annotations instead of doclet comments.": It uses APT and QDox-1.6-SNAPSHOT

**Comment by jira-importer** [comment]
**[Jimisola Laursen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jimisola)** commented

If QDox's non-support of JDK 1.5 (and annotations) is a show-stopper wouldn't it be possible to allow both JavaDoc annotations (for 1.4.x) and Java Annotations (for 1.5+)?
This is how TestNG does - if I am not mistaking. I believe that there are several benefits by allowing developers to use real Java annotations:

- type-safety
- easier to know what values are allowed

The Descriptor Maven Plugin (plugin:descriptor) will be able to use APT (http://java.sun.com/j2se/1.5.0/docs/guide/apt/).
Don't know how far the Maven Annotated Mojo (http://sourceforge.net/projects/mvn-anno-mojo) has come, but it might be possible to use their code since it is licensed used APL 2.0.

**Comment by jira-importer** [comment]
**[Matthew Pocock](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dozer)** commented

This is really annoying for us. Apparently qdox 1.6 is out, and handles java5 syntax gracefully.

http://joe.truemesh.com/blog//000642.html

I have hacked maven-plugin-tools-java-2.0.1.pom to refer to qdox v 1.6, and now everything runs fine for me. Could someone who knows check if this does solve the problem in general, and make the change? Pretty please?

**Comment by jira-importer** [comment]
**[Jimisola Laursen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jimisola)** commented

QDox 1.6. That is really good news. I wonder why QDOX-94 haven't been resolved...

What are the requirements for Maven in general 1.4 or even 1.3?
Don't think that Apache and Codehaus plugins should require 1.5, but I would like to be able touse 1.5 for "internal" plugins.

**Comment by jira-importer** [comment]
**[Albert Strasheim](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fullung)** commented

The workaround I came up with was to but my Java 5 annotation containing code into a separate jar and make a project containing only my mojo which depends on this jar.
