### ISSUE TITLE
[MPLUGIN-20] java.util.MissingResourceException when execute "site" goal.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#440]
**[Willie Vu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=willievu)** opened **[MPLUGIN-20](https://issues.apache.org/jira/browse/MPLUGIN-20?redirect=false)** and commented

[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Can't find bundle for base name plugin-report, locale zh_CN
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.util.MissingResourceException: Can't find bundle for base name plugin-report, locale zh_CN
at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:804)
at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:773)
at java.util.ResourceBundle.getBundle(ResourceBundle.java:661)
at org.apache.maven.plugin.plugin.PluginReport.getBundle(PluginReport.java:200)
at org.apache.maven.plugin.plugin.PluginReport.getName(PluginReport.java:169)
at org.apache.maven.plugins.site.ReportComparator.compare(ReportComparator.java:40)
at java.util.Arrays.mergeSort(Arrays.java:1278)
at java.util.Arrays.sort(Arrays.java:1219)
at java.util.Collections.sort(Collections.java:155)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:240)

Need a default ResourceBundle.  Possible resolution: rename plugin-report_en.properties to plugin-report.properties.

---
No further details from [MPLUGIN-20](https://issues.apache.org/jira/browse/MPLUGIN-20?redirect=false)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

fixed by Vincent in r326881
