### ISSUE TITLE
[MPLUGIN-104] plugin report broken in 2.4

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#466]
**[Brian E Fox](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf)** opened **[MPLUGIN-104](https://issues.apache.org/jira/browse/MPLUGIN-104?redirect=false)** and commented

In 2.4 with 2.0.8 I get:

```
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] org.apache.maven.doxia.siterenderer.Renderer.createSink(Ljava/io/File;Ljava/lang/String;)Lorg/apache/maven/doxia/siterenderer/sink/SiteRendererSink;
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
java.lang.NoSuchMethodError: org.apache.maven.doxia.siterenderer.Renderer.createSink(Ljava/io/File;Ljava/lang/String;)Lorg/apache/maven/doxia/siterenderer/sink/SiteRendererSink;
	at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:63)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:333)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:126)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

---

**Affects:** 2.4

**Issue Links:**
- [MCHANGES-88](https://issues.apache.org/jira/browse/MCHANGES-88) NoSuchMethodError with maven 2.0.8 when generating changes-report

- [MSHARED-13](https://issues.apache.org/jira/browse/MSHARED-13) [maven-reporting-impl] 2.0.4 uses old doxia-site-renderer with obsolete Renderer.createSink(..) call
 (_**"depends upon"**_)

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

I added an IT to reproduce this here: https://svn.apache.org/repos/asf/maven/plugin-tools/trunk/maven-plugin-plugin/src/it

Notice that the IT first calls the report version 2.3 and it works. Report version 2.4 then fails on the same project.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Made a copy of the 2.0.4 tag for maven-reporting-impl to https://svn.apache.org/repos/asf/maven/shared/branches/maven-reporting-impl-2.0.4.1-dev, then adjusted the AbstractMavenReport and SinkFactory to avoid using the Renderer interface for creating Sink instances. Also bumped the doxia dependencies there to 1.0-alpha-10 to keep up with things. The new version is current 2.0.4.1-SNAPSHOT.

Finally, I bumped the maven-reporting-impl version from 2.0.4 to 2.0.4.1-SNAPSHOT to take advantage of the fixes to AbstractMavenReport.
