### ISSUE TITLE
[MPLUGIN-40] All plugins should by default have an auto-generated goal 'help'

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#479]
**[Eirik Maus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eirikma)** opened **[MPLUGIN-40](https://issues.apache.org/jira/browse/MPLUGIN-40?redirect=false)** and commented

All plugins should have a goal called "help" providing help on how to use the plugin. This should be auto-generated if it doesn't already exist as a goal in the mojo. The autogenerated help should typically list the goals (and settable properties) of the plugin, and probably also print out the url to the plugin's website (if available). This will most likely affect the plugin archetype as well, I guess.

---

**Affects:** 2.3

**Issue Links:**
- [MPH-27](https://issues.apache.org/jira/browse/MPH-27) Each plugin should have a help goal
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Tobias Roeser](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lefou)** commented

This is not working with the current maven-plugin-plugin (version 2.3).

I couldn't find the svn repository to this plugin, just the tags svn repo with version 2.3 which is to old.

The error message is:

[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] 'helpmojo' was specified in an execution, but not found in the plugin
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: 'helpmojo' was specified in an execution, but not found in the plugin
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindExecutionToLifecycle(DefaultLifecycleExecutor.java:1342)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindPluginToLifecycle(DefaultLifecycleExecutor.java:1243)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecycleMappings(DefaultLifecycleExecutor.java:987)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:333)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:126)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:282)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Fri Feb 01 11:40:00 CET 2008
[INFO] Final Memory: 3M/68M
[INFO] ------------------------------------------------------------------------
