### ISSUE TITLE
[MPLUGIN-149] ParseException with annotation @XmlType in JavaDocBuilder

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#488]
**[Jean-Paul GUIGUI](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jguigui)** opened **[MPLUGIN-149](https://issues.apache.org/jira/browse/MPLUGIN-149?redirect=false)** and commented

I'm generating code from the template changes-1.0.0.xsd with Jaxb and the code generated is used by an in-house maven plugin.
There is a regression in the maven-plugin-plugin: with version 2.4.2 is used to work properly, now with version 2.4.3 and 2.5 the plugin:descriptor task is failing with a ParseException.

The JavaDocBuilder is not able to parse the following lines:
`@XmlAccessorType`(XmlAccessType.FIELD)
`@XmlType`(name = "ChangesDocument", namespace = "http://maven.apache.org/changes/1.0.0", propOrder = {

})

It is failing with both mvn 2.09 and 2.1.0

[INFO] [plugin:descriptor]
[INFO] Using 2 extractors.
[INFO] Applying extractor for language: java
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] syntax error @[44,1] in file:/C:/MyProject/target/generated-sources/jaxb/myproject/jaxb/ChangesDocument.java
[INFO] ------------------------------------------------------------------------
[INFO] Trace
com.thoughtworks.qdox.parser.ParseException: syntax error @[44,1] in file:/C:/MyProjects/target/generated-sources/jaxb/myproject/ChangesDocument.java
at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:716)
at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:826)
at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:697)
at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:300)
at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:316)
at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:312)
at com.thoughtworks.qdox.JavaDocBuilder$1.visitFile(JavaDocBuilder.java:369)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:43)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34)
at com.thoughtworks.qdox.directorywalker.DirectoryScanner.scan(DirectoryScanner.java:52)
at com.thoughtworks.qdox.JavaDocBuilder.addSourceTree(JavaDocBuilder.java:366)
at org.apache.maven.tools.plugin.extractor.java.JavaMojoDescriptorExtractor.discoverClasses(JavaMojoDescriptorEx
tractor.java:605)
at org.apache.maven.tools.plugin.extractor.java.JavaMojoDescriptorExtractor.execute(JavaMojoDescriptorExtractor.
java:572)
at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:96)

    at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:146)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:54

0) 

       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:519)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav

a:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

**Affects:** 2.5

**Attachments:**
- [gmi.xsd](https://issues.apache.org/jira/secure/attachment/12717586/gmi.xsd) (_8.78 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12717563/pom.xml) (_1.45 kB_)

**Issue Links:**
- [MPLUGIN-151](https://issues.apache.org/jira/browse/MPLUGIN-151) ParseException on enum members with annotations that have values

- [MPLUGIN-150](https://issues.apache.org/jira/browse/MPLUGIN-150) Update to QDox 1.9.2
 (_**"depends upon"**_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

You could try adding

```xml
<dependency>
  <groupId>com.thoughtworks.qdox</groupId>
  <artifactId>qdox</artifactId>
  <version>1.9</version>
</dependency>
```

as dependency of the maven-plugin-plugin and see whether this makes a difference.

**Comment by jira-importer** [comment]
**[Jean-Paul GUIGUI](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jguigui)** commented

Thanks a lot. Working fine.

```xml
<plugin>
 <groupId>org.apache.maven.plugins</groupId>
 <artifactId>maven-plugin-plugin</artifactId>
 <version>2.5</version>
 <dependencies>
  <dependency>
   <groupId>com.thoughtworks.qdox</groupId>
   <artifactId>qdox</artifactId>
   <version>1.9</version>
  </dependency>
 </dependencies>	
</plugin>
```

Could you make it the default version for the next release ?

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed by updating to QDox 1.9.1

**Comment by jira-importer** [comment]
**[Klyuchnikov Eugene](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eustas)** commented

neither workaround, 2.5.1-SNAPSHOT, nor 2.4.2 helps in project with attached gmi.xsd

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Eugene, your slightly different issue is tracked in MPLUGIN-151.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

QDox 1.9.2 has just been released, using this as the plugin dependency as described above should fix this.
