### ISSUE TITLE
[MPLUGIN-102] The 2.4 Release Breaks Previously-Working Builds

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#520]
**[James Carman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jwcarman)** opened **[MPLUGIN-102](https://issues.apache.org/jira/browse/MPLUGIN-102?redirect=false)** and commented

We have an archetype contained within our project.  Today, when I tried to run our build, I got the following error:

[INFO] [plugin:descriptor]
[INFO] Using 2 extractors.
[INFO] Applying extractor for language: java
[INFO] Extractor for language: java found 0 mojo descriptors.
[INFO] Applying extractor for language: bsh
[INFO] Extractor for language: bsh found 0 mojo descriptors.
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error extracting plugin descriptor: 'No mojo descriptors found in plugin.'

However, if I add this to my pom.xml file for that module:

\<pluginManagement>
\<plugins>
\<plugin>
\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-plugin-plugin\</artifactId>
\<version>2.3\</version>
\</plugin>
\</plugins>
\</pluginManagement>
the build works just fine, as usual (understandable since the 2.4 release came out yesterday).

---

**Affects:** 2.4

**Attachments:**
- [archetype-test.zip](https://issues.apache.org/jira/secure/attachment/12717585/archetype-test.zip) (_4.71 kB_)
- [debug.log](https://issues.apache.org/jira/secure/attachment/12717597/debug.log) (_40.98 kB_)

**Issue Links:**
- [MPLUGIN-106](https://issues.apache.org/jira/browse/MPLUGIN-106) remove no mojo deprecation warning and throw an exception

- [MPLUGIN-103](https://issues.apache.org/jira/browse/MPLUGIN-103) Plugins without descriptors

- [MPLUGIN-103](https://issues.apache.org/jira/browse/MPLUGIN-103) Plugins without descriptors
 (_**"depends upon"**_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

The plugin-plugin works in other cases so the problem is likely caused by something specific to your project/environment. Could you please attach a debug log of Maven and if possible some test project to reproduce this? Just from your description it's really hard to start the bug search.

As a side note: For best build reproducibility, consider to always specify fixed versions for the plugins you employ during the build. This adds a little more clutter to the POM but frees you from such surprises. If you have a parent POM, its \<pluginManagement> section is a good place to do this centrally.

**Comment by jira-importer** [comment]
**[James Carman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jwcarman)** commented

Here's an example project.

**Comment by jira-importer** [comment]
**[James Carman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jwcarman)** commented

Yes, I'm currently in the process of locking down all versions of our project's plugins.  This seems to be quite tedious.  I was trying to use the enforcer plugin, but it has its own problems:

http://jira.codehaus.org/browse/MENFORCER-25

Is there an easy way to ask "what are all my plugins I'm using and what are the current versions"?  Better yet, I'd love to be able to do:

mvn plugin:lockdown-current

**Comment by jira-importer** [comment]
**[James Carman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jwcarman)** commented

By the way, the Tapestry folks also ran into this issue.  Have a look:

https://issues.apache.org/jira/browse/TAPESTRY-1914

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Caused by change for MPLUGIN-103 applied in [r543359](http://svn.apache.org/viewvc?view=rev&revision=543359).

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Other comments on your test case:

Adding the following

```
<reporting>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-plugin-plugin</artifactId>
            <version>2.4</version>
        </plugin>
    </plugins>
</reporting>
```

mvn site fails with a NPE on maven-plugin-plugin 2.3 or bellow but produces your error on 2.4

**Comment by jira-importer** [comment]
**[Leonardo Uribe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lu4242)** commented

I have the same error running archetypes with 2.4

The log is this:

[INFO]   Apache MyFaces Trinidad Archetype
[INFO]   MyFaces Archetype
[INFO]   MyFaces Archetype Facelets
[INFO]   MyFaces Portlet Archetype
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache MyFaces Buildtools Maven2 Archetype Parent
[INFO]    task-segment: [clean, install]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean]
[INFO] [site:attach-descriptor]
[INFO] [install:install]
[INFO] Installing C:\GSOC\workspace\maven2-archetypes\pom.xml to C:\Documents and Settings\Leonardo\.m2\repository\org\apache\myfaces\buildtools\myfaces-archetype-parent\1.0.1-SNAPSHOT\myfaces-archetype-parent-1.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Building JSF Components Library Archetype
[INFO]    task-segment: [clean, install]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean]
[INFO] Deleting directory C:\GSOC\workspace\maven2-archetypes\myfaces-archetype-jsfcomponents\target
[INFO] [plugin:descriptor]
[INFO] Using 2 extractors.
[INFO] Applying extractor for language: java
[INFO] Extractor for language: java found 0 mojo descriptors.
[INFO] Applying extractor for language: bsh
[INFO] Extractor for language: bsh found 0 mojo descriptors.
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error extracting plugin descriptor: 'No mojo descriptors found in plugin.'

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error extracting plugin descriptor: 'No mojo descriptors found in plugin.'
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:564)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:333)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:126)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:282)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error extracting plugin descriptor: 'No mojo descriptors found in plugin.'
at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:149)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
... 16 more
Caused by: org.apache.maven.plugin.descriptor.InvalidPluginDescriptorException: No mojo descriptors found in plugin.
at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:107)
at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:137)
... 18 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5 seconds
[INFO] Finished at: Wed Mar 19 20:32:46 COT 2008
[INFO] Final Memory: 11M/254M
[INFO] ------------------------------------------------------------------------

getting back to 2.3 make this work again
