### ISSUE TITLE
[MPLUGIN-119] Regression when generating site (mojo description pages) for my own maven plugins

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#560]
**[Guimiot Isabelle](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iguimiot)** opened **[MPLUGIN-119](https://issues.apache.org/jira/browse/MPLUGIN-119?redirect=false)** and commented

I have developped several maven plugins for my project, and each time I deliver a new version, I generate the plugin site, with mojo pages (xxx-mojo.html) describing each goal and its parameters.

The description found in these pages is based on the javadoc that I wrote in my java mojo classes, and as I'm french, I use accents in my javadoc (java source code encoded in ISO-8859-1). The generation has 2 steps : first, an xdoc file is created in target/generated-site/xdoc, and second, the html file is generated from the xdoc.

When I was using maven 2.0.8 and older versions, the xdoc was containing real accents and I had no problem during the build, and the html file was good.
Now, with maven 2.0.9, the xdoc contains "& eacute;" characters instead of accents, and when the build generates the site, this exception is raising :

[ERROR] Error parsing C:\wks\maven-mypersonal-plugin\target\generated-site\xdoc\mypersonalgoal-mojo.xml: line [-1] Error parsing the model.
org.apache.maven.doxia.parser.ParseException: Error parsing the model.
at org.apache.maven.doxia.module.xdoc.XdocParser.parse(XdocParser.java:55)
at org.apache.maven.doxia.DefaultDoxia.parse(DefaultDoxia.java:52)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderDocument(DefaultSiteRenderer.java:264)
at org.apache.maven.doxia.siterenderer.DoxiaDocumentRenderer.renderDocument(DoxiaDocumentRenderer.java:43)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:239)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:115)
at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:132)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:92)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: could not resolve entity named 'eacute' (position: START_TAG seen ...\<p>Ce goal supprime le contenu du r&eacute;... `@11`:50)
at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1282)
at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1093)
at org.apache.maven.doxia.module.xdoc.XdocParser.parseXdoc(XdocParser.java:312)
at org.apache.maven.doxia.module.xdoc.XdocParser.parse(XdocParser.java:51)
... 25 more

It's a minor bug, because it only happens when I call "mvn install site" in a single mvn command. When I first launch "mvn install", and then "mvn site", it works fine ! I really don't know why...

---

**Affects:** 2.4

**Issue Links:**
- [MPLUGIN-96](https://issues.apache.org/jira/browse/MPLUGIN-96) Handle character encoding properly in makeHtmlValid()

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

The problem is unrelated to Maven itself, the XDoc is generated by the maven-plugin-plugin. The regression was introduced by usage of JTidy to cleanup the HTML fragments extracted from the Javadoc, starting with version 2.4 of the maven-plugin-plugin. The bug has already been fixed in SVN by MPLUGIN-96. Until version 2.4.2 of the maven-plugin-plugin gets released, I suggest you lock down the version of the plugin to 2.3 which does not expose the bug.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> t's a minor bug, because it only happens when I call "mvn install site" in a single mvn command. When I first launch "mvn install", and then "mvn site", it works fine ! I really don't know why...
> I assume you use two different versions of the maven-plugin, namely 2.3 for the site generation and 2.4 for the build. When you invoke the phases "install" and "site" on the same command line, Maven will (by error) only use the plugin version it encountered first, which is 2.4 for the "install" phase. When version 2.4 is used for the site, it fails. You could enable Maven's debug output via the flag `-X` to check the version of maven-plugin-plugin.

**Comment by jira-importer** [comment]
**[Guimiot Isabelle](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iguimiot)** commented

Thanks for your comments, you're right, I had the plugin-plugin version set in the reporting tag, but nothing in the build tag. Now, it works fine !
