### ISSUE TITLE
[MPLUGIN-186] Plugins with no mojos lead to exception and failure in PluginReport

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#562]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** opened **[MPLUGIN-186](https://issues.apache.org/jira/browse/MPLUGIN-186?redirect=false)** and commented

If a plugin has no mojos, because it exists purely to add a lifecycle, a backtrace and failure reports:

I'm just supplying the tail of it.

Caused by: org.apache.maven.reporting.MavenReportException: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: org.eclipse.tycho:tycho-maven-plugin.'
at org.apache.maven.plugin.plugin.PluginReport.executeReport(PluginReport.java:231)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:135)
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:228)
... 25 more
Caused by: org.apache.maven.plugin.descriptor.InvalidPluginDescriptorException: No mojo definitions were found for plugin: org.eclipse.tycho:tycho-maven-plugin.
at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:121)
at org.apache.maven.plugin.plugin.PluginReport.executeReport(PluginReport.java:219)
... 27 more

---

**Affects:** 2.8

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

This jira is in the wrong place. It needs to stick to 'PluginReport', not 'PluginsReport'. I'll fix it.
