### ISSUE TITLE
[MPLUGIN-114] PluginXdocGenerator NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#564]
**[Garvin Leclaire](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gleclaire)** opened **[MPLUGIN-114](https://issues.apache.org/jira/browse/MPLUGIN-114?redirect=false)** and commented

When creating a site I get the following stack trace:

[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.tools.plugin.generator.PluginXdocGenerator.execute(PluginXdocGenerator.java:95)
at org.apache.maven.plugin.plugin.PluginReport.generatePluginDocumentation(PluginReport.java:224)
at org.apache.maven.plugin.plugin.PluginReport.executeReport(PluginReport.java:178)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:90)
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:269)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:101)
at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:129)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:96)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:333)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:126)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:282)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33 seconds
[INFO] Finished at: Wed May 14 23:36:51 EDT 2008
[INFO] Final Memory: 41M/63M

I have tried and get the same results with version of the site plg-in back to 2.0-beta-3

Any suggestions??

---

**Affects:** 2.3

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12717595/pom.xml) (_4.59 kB_)

**Issue Links:**
- [MNG-2087](https://issues.apache.org/jira/browse/MNG-2087) NPE in PluginXdocGenerator

- [MPLUGIN-65](https://issues.apache.org/jira/browse/MPLUGIN-65) [PATCH] NPE in PluginXDocGenerator while creating plugin site

**Comment by jira-importer** [comment]
**[Garvin Leclaire](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gleclaire)** commented

I tried version 2.3 to 2.4.2-SNAPSHOT of the maven-plugin-plugin.  I am using Maven 2.0.8 on OSX.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

In version 2.4 and 2.4.1 of the maven-plugin-tools-api the line PluginXdocGenerator.java:95 is

```java
for ( Iterator it = pluginDescriptor.getMojos().iterator(); it.hasNext(); )
```

so either the plugin descriptor or its mojo collection seems to be null.

Is there a possibility to get your POM and a full debug output from Maven? Are you working on an open-source project that I could checkout by myself to reproduce this?

**Comment by jira-importer** [comment]
**[Garvin Leclaire](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gleclaire)** commented

I am using the GMaven stuff to work on the Find-bugs-plugin.  If I try to generate a site for the sample GMaven plugins I get the same stack dump.

Looking at the code above there is a bug in it since there is not a null check before working on the iterator.  It seem this was brought up some time ago in [MNG-2087](http://jira.codehaus.org/browse/MNG-2087) .  It looks as though it may have been fixed and then the problem was reintroduced later.

**Comment by jira-importer** [comment]
**[Garvin Leclaire](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gleclaire)** commented

Here is a copy of the pom I am using.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> Looking at the code above there is a bug in it since there is not a null check before working on the iterator.
> Just because a line triggers a NPE does not mean this same line is faulty. The question I would like to investigate on is whether the plugin descriptor is properly crafted, i.e. whether the null list is a valid return value.

> It seem this was brought up some time ago in MNG-2087
> There seem to more than one occasion where people reported NPEs because collections were null rather than empty. As I don't currently see a rationale to distinguish a null collection from an empty collection, I believe it's time to fix the descriptors themselves rather to add null checks in every piece of code that processes them.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r657562](http://svn.apache.org/viewvc?view=rev&revision=657562). The crap with the null collection goes deep down to Plexus which can only be updated in combination with the Maven core...

Thanks for the POM, that helped a lot. However, there seems to be something else wrong: Now you end up with an empty goal documentation for the Findbugs Plugin. If this is not a problem on the Groovy side, please fill in another ticket.

**Comment by jira-importer** [comment]
**[Garvin Leclaire](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gleclaire)** commented

I am digging in the Groovy plugin code to confirm if there is an bug there.

Thanks.

**Comment by jira-importer** [comment]
**[Marc Lustig](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=axismundi)** commented

using 2.4.2-SNAPSHOT, I get

java.lang.NullPointerException
at org.apache.maven.tools.plugin.generator.PluginXdocGenerator.execute(PluginXdocGenerator.java:96)

---> still a NPE, just one line below

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> using 2.4.2-SNAPSHOT
> At the time of your post, the latest snapshot dated back to April the 17th, I closed this issue May the 18th.

New Snapshots have been deployed.
