### ISSUE TITLE
[MPLUGIN-269] maven-plugin-tools-annotations does not work in builds which don't package

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#575]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** opened **[MPLUGIN-269](https://issues.apache.org/jira/browse/MPLUGIN-269?redirect=false)** and commented

When running descriptor goal inside m2e workspace, I get the following exception for plugin projects that depend on other plugin projects.

```
org.apache.maven.plugin.PluginExecutionException: Execution default-descriptor of goal org.apache.maven.plugins:maven-plugin-plugin:3.3:descriptor failed: The source must not be a directory.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:328)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$10.call(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$10.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:174)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:110)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1353)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:132)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:174)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:110)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:174)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:149)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:97)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: org.codehaus.plexus.archiver.ArchiverException: The source must not be a directory.
	at org.codehaus.plexus.archiver.AbstractUnArchiver.validate(AbstractUnArchiver.java:185)
	at org.codehaus.plexus.archiver.AbstractUnArchiver.extract(AbstractUnArchiver.java:118)
	at org.apache.maven.tools.plugin.annotations.JavaAnnotationsMojoDescriptorExtractor.discoverClassesFromSourcesJar(JavaAnnotationsMojoDescriptorExtractor.java:220)
	at org.apache.maven.tools.plugin.annotations.JavaAnnotationsMojoDescriptorExtractor.scanJavadoc(JavaAnnotationsMojoDescriptorExtractor.java:172)
	at org.apache.maven.tools.plugin.annotations.JavaAnnotationsMojoDescriptorExtractor.execute(JavaAnnotationsMojoDescriptorExtractor.java:100)
	at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:96)
	at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:243)
	at org.apache.maven.plugin.plugin.DescriptorGeneratorMojo.execute(DescriptorGeneratorMojo.java:90)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 31 more
```

As a result, plugin.xml is not generated and the plugin cannot be used from m2e workspace directly.

The same exception is thrown during multimodule reactor build invoked with "mvn clean process-classes -e".

---
No further details from [MPLUGIN-269](https://issues.apache.org/jira/browse/MPLUGIN-269?redirect=false)

**Comment by jira-importer** [comment]
**[Tobias Oberlies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tobias.oberlies)** commented

Sorry, I don't have a minimal project yet, but here is one way to reproduce this issue:
* Get the Tycho sources from https://git.eclipse.org/r/tycho/org.eclipse.tycho
* Run `mvn clean process-classes -am -pl tycho-source-plugin`

I've debugged the code, and found the following code location where maven-plugin-tools-annotations-3.3 goes wrong: When looking up artifacts from the reactor at JavaAnnotationsMojoDescriptorExtractor.getFromProjectReferences(Artifact, MavenProject) line 716, it compares `mavenProject.getId()` (a reactor artifact) and `artifact.getId()`. The artifact should be found in the reactor, but it isn't because
* the former returns `org.eclipse.tycho:tycho-packaging-plugin:maven-plugin:0.22.0-SNAPSHOT`, and
* the latter returns `org.eclipse.tycho:tycho-packaging-plugin:jar:0.22.0-SNAPSHOT`

**Comment by jira-importer** [comment]
**[Tobias Oberlies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tobias.oberlies)** commented

However the question is why `getFromProjectReferences` is attempted at all. After failing to match the above IDs, `discoverClassesFromSourcesJar` correctly finds the `tycho-packaging-plugin` in the reactor. It only fails to check the type of `sourcesArtifact.getFile()` but blindly assumes that the method returns a jar. However this is not the case if the build is started with a phase which does not include `package`.

So really this bug should be easy to fix with a few lines of code change.

**Comment by jira-importer** [comment]
**[Tobias Oberlies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tobias.oberlies)** commented

> The link doesn't work, but I've tried to reproduce it. This made me wonder: what is the packaging-type of the dependency? I guess you haven't specified it, so it falls back to the default, which is jar. In that case the code is correct.

You are right, we didn't specify a packaging type. Adding `<type>maven-plugin</type>` in the dependency fixed the problem. Thanks for the pointer.
