### ISSUE TITLE
[MPLUGIN-303] Plugin Plugin breaks when ASM6.0_ALPHA is configured as dependency

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#608]
**[Andrew Dinn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adinn)** opened **[MPLUGIN-303](https://issues.apache.org/jira/browse/MPLUGIN-303?redirect=false)** and commented

When the latest (3.0.7) Byteman project pom dependency on the ASM library is upgraded from 5.0.3 to 6.0_ALPHA building  of  Byteman's maven rulechceck plugin fails. If the version is reverted to 5.0.3 the plugin builds without problem.

Note that although this upgrade is needed in order to allow Byteman to transform JDK9 class files no such files need to be present in the build for the problme to manifest.  The failure occurs when building Byteman with JDK7, JDK8 or JDK9. The ASM library and Byteman source do not use features beyond JDK6. The Byteman build is configured with source and target level 1.6 The ASM library has source and target 1.4.

---

**Affects:** 3.4

**Issue Links:**
- [MPLUGIN-304](https://issues.apache.org/jira/browse/MPLUGIN-304) MojoAnnotationsScanner should ignore special classes

- [MPLUGIN-304](https://issues.apache.org/jira/browse/MPLUGIN-304) MojoAnnotationsScanner should ignore special classes
 (_**"is superceded by"**_)

**Comment by jira-importer** [comment]
**[Andrew Dinn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adinn)** commented

I am running on fedora 22 using mvn 3.3.3

The problem can be reproduced by checking out the Byteman project from the master github repo (https://github.com/bytemanproject/byteman), modifying the dependency for asm in the top level pom to specif version AMS6.0_ALPHA i.e. change

```xml
 <!-- External dependencies -->
<dependency>
     <groupId>org.ow2.asm</groupId>
     <artifactId>asm-all</artifactId>
     <version>5.0.3</version>
```

to

```xml
 <!-- External dependencies -->
<dependency>
     <groupId>org.ow2.asm</groupId>
     <artifactId>asm-all</artifactId>
     <version>6.0_ALPHA</version>
```

and then running `mvn clean install -X -e`. The resulting error output ends with the following

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.4:helpmojo (help-goal) on project byteman-rulecheck-maven-plugin: Execution help-goal of goal org.apache.maven.plugins:maven-plugin-plugin:3.4:helpmojo failed. IllegalArgumentException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.4:helpmojo (help-goal) on project byteman-rulecheck-maven-plugin: Execution help-goal of goal org.apache.maven.plugins:maven-plugin-plugin:3.4:helpmojo failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution help-goal of goal org.apache.maven.plugins:maven-plugin-plugin:3.4:helpmojo failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.analyzeClassStream(DefaultMojoAnnotationsScanner.java:201)
	at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.scanArchive(DefaultMojoAnnotationsScanner.java:139)
	at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.scan(DefaultMojoAnnotationsScanner.java:108)
	at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.scan(DefaultMojoAnnotationsScanner.java:75)
	at org.apache.maven.tools.plugin.extractor.annotations.JavaAnnotationsMojoDescriptorExtractor.scanAnnotations(JavaAnnotationsMojoDescriptorExtractor.java:124)
	at org.apache.maven.tools.plugin.extractor.annotations.JavaAnnotationsMojoDescriptorExtractor.execute(JavaAnnotationsMojoDescriptorExtractor.java:103)
	at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:96)
	at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:245)
	at org.apache.maven.plugin.plugin.HelpGeneratorMojo.execute(HelpGeneratorMojo.java:92)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
```

**Comment by jira-importer** [comment]
**[Paul Benedict](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paul4christ79)** commented

The ASM used by the Plugin Plugin chokes on reading the new module-info.class file found in your project's ASM. The problem is the Plugin Plugin scans all dependencies of your project for other mojo annotations. MPLUGIN-304 should be the official solution. In the mean time, delete module-info.class out of your copy of ASM6.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed with MPLUGIN-304
