### ISSUE TITLE
[MPLUGIN-299] Help mojo cannot display goal details

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#611]
**[Harald Wellmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hwellmann)** opened **[MPLUGIN-299](https://issues.apache.org/jira/browse/MPLUGIN-299?redirect=false)** and commented

Given a Mojo with `@Parameter` annotations **without** any further annotation arguments like `property` or `defaultValue`, when invoking the generated help mojo for details

```
mvn myplugin:help -Dgoal=mygoal -Ddetail=true
```

then the Mojo fails with a NullPointerException:

```
Caused by: java.lang.NullPointerException
        at org.ops4j.pax.warp.maven.HelpMojo.findNamedChild(HelpMojo.java:203)
        at org.ops4j.pax.warp.maven.HelpMojo.findSingleChild(HelpMojo.java:218)
        at org.ops4j.pax.warp.maven.HelpMojo.writeParameter(HelpMojo.java:276)
        at org.ops4j.pax.warp.maven.HelpMojo.writeGoal(HelpMojo.java:264)
        at org.ops4j.pax.warp.maven.HelpMojo.execute(HelpMojo.java:164)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
```

---

**Affects:** 3.4

**Comment by jira-importer** [comment]
**[Harald Wellmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hwellmann)** commented

In this case, the `<mojo>` element of `plugin-help.xml` does not contain a `<configuration>` child element, but the `writeParameter()` method of the generated `HelpMojo` tries to access a child of the non-existing `<configuration>` child element.

Workaround:

Add a `property`  or `defaultValue` member to at least one of the `@Parameter` annotations.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed in [r1756221](http://svn.apache.org/viewvc?rev=1756221&view=rev)
