### ISSUE TITLE
[MPLUGIN-328] ArrayIndexOutOfBoundsException: 48188 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#636]
**[zosrothko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zosrothko)** opened **[MPLUGIN-328](https://issues.apache.org/jira/browse/MPLUGIN-328?redirect=false)** and commented

Hi

Got a ArrayIndexOutOfBoundsException on the maven-plugin-plugin:3.5 with an empty execution element

```xml
<plugin>
  <artifactId>maven-plugin-plugin</artifactId>
  <version>3.5</version>
</plugin>
```

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.5:descriptor (default-descriptor) on project scortes-maven-plugin: Execution default-descriptor of goal org.apache.maven.plugins:maven-plugin-plugin:3.5:descriptor failed: 48188 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.5:descriptor (default-descriptor) on project scortes-maven-plugin: Execution default-descriptor of goal org.apache.maven.plugins:maven-plugin-plugin:3.5:descriptor failed: 48188
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-descriptor of goal org.apache.maven.plugins:maven-plugin-plugin:3.5:descriptor failed: 48188
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 48188
        at org.objectweb.asm.ClassReader.readClass(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.analyzeClassStream(DefaultMojoAnnotationsScanner.java:215)
        at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.scanArchive(DefaultMojoAnnotationsScanner.java:145)
        at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.scan(DefaultMojoAnnotationsScanner.java:112)
        at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.scan(DefaultMojoAnnotationsScanner.java:79)
        at org.apache.maven.tools.plugin.extractor.annotations.JavaAnnotationsMojoDescriptorExtractor.scanAnnotations(JavaAnnotationsMojoDescriptorExtractor.java:124)
        at org.apache.maven.tools.plugin.extractor.annotations.JavaAnnotationsMojoDescriptorExtractor.execute(JavaAnnotationsMojoDescriptorExtractor.java:103)
        at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:96)
        at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:283)
        at org.apache.maven.plugin.plugin.DescriptorGeneratorMojo.execute(DescriptorGeneratorMojo.java:90)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

---

**Affects:** 3.5

**Attachments:**
- [MPLUGIN_328_ArrayIndexOutOfBoundsException__48188.patch](https://issues.apache.org/jira/secure/attachment/12904484/MPLUGIN_328_ArrayIndexOutOfBoundsException__48188.patch) (_1.27 kB_)
- [plugin.rar](https://issues.apache.org/jira/secure/attachment/12906197/plugin.rar) (_33.46 kB_)
- [plugin.zip](https://issues.apache.org/jira/secure/attachment/12901635/plugin.zip) (_33.46 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12901634/pom.xml) (_17.61 kB_)

**Issue Links:**
- [MPLUGIN-305](https://issues.apache.org/jira/browse/MPLUGIN-305) MojoAnnotationsScanner should have better control over dependency scanning

**Remote Links:**
- [GitHub Pull Request #11
](https://github.com/apache/maven-plugin-tools/pull/11)

2 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Sample project please.

**Comment by jira-importer** [comment]
**[zosrothko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zosrothko)** commented

Sample project provided in plugin.zip as well as its parent project as pom.xml

**Comment by jira-importer** [comment]
**[Daniel Heid](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dheid)** commented

I changed the default annotation scanner to just print a warning in case a class could not be analyzed. This should not let a build fail. In my case, I added a dependency compiled with AspectJ and that leads to a build interruption.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

[zosrothko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zosrothko) I can't open plugin.zip file, it seems the file is corrupted: can you provide a new one, please?

a workaround that should work immediately with maven-plugin-plugin 3.5 is to use `mojoDependencies` configuration to scan only useful dependencies: see MPLUGIN-305
(I suppose AspectJ classes that cause a failure are not Mojo subclasses, then not really useful to scan)

Before committing another workaround, I need a sample failure to add as integration test: I can't add code based only on reasoning or people telling they tested

**Comment by jira-importer** [comment]
**[zosrothko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zosrothko)** commented

[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy): Uploaded a new attachement plugin.rar build with WinRAR. BTW, WinRAR is opening without any problem plugin.zip

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

ok, I can open plugin.rar. BTW, I can open plugin.zip with unrar: it's not a zip file but a rar file with unusual extension...

And I was able to reproduce the issue: working on it

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

ok, issue analyzed, plugin improvement ready, but I need to make the IT more simple.
In fact, in this testcase, ASM is choking on `com/ibm/icu/impl/data/LocaleElements_zh__PINYIN.class` in `com.ibm.icu:icu4j:2.6.1` dependency
then using MPLUGIN-305 dependency filtering feature would permit you to workaround the issue

Not using `java-annotations` mojo extractor would also solve the issue, since you're using javadoc annotations, but I suppose javadoc annotations are not so common nowadays: Java 5 annotations are more convenient, since strongly typed

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

I catched ArrayIndexOutOfBoundsException on ASM run: is it the only type of runtime exception that happens?

[Daniel Heid](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dheid) is it exactly the same for your AspectJ case?

**Comment by jira-importer** [comment]
**[Daniel Heid](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dheid)** commented

Yes, absolutely: In my case the ArrayIndexOutOfBoundsException was thrown because of an "illegal" class within an external dependency.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

perfect

warn instead of failure implemented in https://gitbox.apache.org/repos/asf?p=maven-plugin-tools.git&a=commit&h=2bc1364372a5285a6ac9b95c65c711e3ada3bbea with IT to check
