### ISSUE TITLE
[MPLUGIN-502] NPE in EnhancedPluginDescriptorBuilder with Maven 4.x

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#806]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** opened **[MPLUGIN-502](https://issues.apache.org/jira/browse/MPLUGIN-502?redirect=false)** and commented

With Maven 4.x (4.0.0-alpha-10) we have:

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.codehaus.plexus.configuration.PlexusConfiguration.getChild(String)" because "this.configuration" is null
    at org.apache.maven.plugins.plugin.descriptor.EnhancedPluginDescriptorBuilder.build(EnhancedPluginDescriptorBuilder.java:75)
    at org.apache.maven.plugin.descriptor.PluginDescriptorBuilder.build(PluginDescriptorBuilder.java:63)
    at org.apache.maven.plugin.plugin.report.PluginReport.extractPluginDescriptor(PluginReport.java:163)
    at org.apache.maven.plugin.plugin.report.PluginReport.executeReport(PluginReport.java:148)
    at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:289)
```

Also ITs in  `maven-plugin-report-plugin` fails with Maven 4.x

---

**Affects:** 3.10.2, 3.11.0

**Issue Links:**
- [MPLUGIN-507](https://issues.apache.org/jira/browse/MPLUGIN-507) NPE during plugin run in Creadur RAT to generate mojo descriptor - only Maven 4.x-related
 (_**"is duplicated by"**_)
- [MNG-8714](https://issues.apache.org/jira/browse/MNG-8714) maven-site-plugin with Maven master fails

- [MDEP-948](https://issues.apache.org/jira/browse/MDEP-948) building site with Maven 4 throws NPE saying "this.configuration" is null

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I see:

```
[INFO] --------------------------------------------------------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.3.0:install (integration-test) on project maven-plugin-plugin: Failed to install project dependencies: MavenProject: org.apache.maven.plugins:maven-plugin-plugin:3.10.0 @ D:\Entwicklung\Projekte\maven-plugin-tools\maven-plugin-plugin\pom.xml: Failed to install project artifacts: MavenProject: org.apache.maven.plugin-tools:maven-plugin-tools-ant:3.10.0 @ D:\Entwicklung\Projekte\maven-plugin-tools\maven-script\maven-plugin-tools-ant\pom.xml: Failed to install artifact: org.apache.maven.plugin-tools:maven-plugin-tools-ant:pom:consumer:3.10.0: transformed artifact file cannot be set -> [Help 1]
[INFO] --------------------------------------------------------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.3.0:install (integration-test) on project maven-plugin-plugin: Failed to install project dependencies: MavenProject: org.apache.maven.plugins:maven-plugin-plugin:3.10.1 @ D:\Entwicklung\Projekte\maven-plugin-tools\maven-plugin-plugin\pom.xml: Failed to install project artifacts: MavenProject: org.apache.maven.plugin-tools:maven-plugin-tools-api:3.10.1 @ D:\Entwicklung\Projekte\maven-plugin-tools\maven-plugin-tools-api\pom.xml: Failed to install artifact: org.apache.maven.plugin-tools:maven-plugin-tools-api:pom:consumer:3.10.1: transformed artifact file cannot be set -> [Help 1]
```

and with 3.10.2+:

```
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 1, Failed: 10, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  fix-maven-since-3.x\pom.xml
[ERROR] *  mplugin-191\pom.xml
[ERROR] *  mplugin-319_report-since\pom.xml
[ERROR] *  mplugin-394_report-encoding\pom.xml
[ERROR] *  plugin-info-jdk\pom.xml
[ERROR] *  plugin-info-jdk-default-version\pom.xml
[ERROR] *  plugin-report\pom.xml
[ERROR] *  plugin-report-annotations\pom.xml
[ERROR] *  plugin-report-requirements-history\pom.xml
[ERROR] *  plugin-report-with-javadoc-links\pom.xml
```

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

invoker 3.6.0 with fix is used in current master branch ...

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Interesting, which of those commits do fix this issue?

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

Fix was in MINVOKER-313
https://github.com/apache/maven-invoker-plugin/pull/174

**Comment by slachiewicz** [comment]
Fixed on the invoker side by MINVOKER-313 (apache/maven-invoker-plugin#174), as noted above; nothing left in plugin-tools.
