### ISSUE TITLE
[MPLUGIN-221] DefaultMojoAnnotationsScanner fails to scan some dependencies

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#884]
**[Tony Chemit](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tchemit)** opened **[MPLUGIN-221](https://issues.apache.org/jira/browse/MPLUGIN-221?redirect=false)** and commented

there is some dependencies which fails on scan, for example

```
<groupId>com.ibm.icu</groupId>
<artifactId>icu4j</artifactId>
```

Will cause this error (I add a log comment to obtain bad class):

```
[ERROR] Error while analyzing class com/ibm/icu/impl/data/LocaleElements_zh__PINYIN.class
java.lang.ArrayIndexOutOfBoundsException: 48188
	at org.objectweb.asm.ClassReader.readClass(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.apache.maven.tools.plugin.annotations.scanner.DefaultMojoAnnotationsScanner.scanFile(DefaultMojoAnnotationsScanner.java:141)
	at org.apache.maven.tools.plugin.annotations.scanner.DefaultMojoAnnotationsScanner.scan(DefaultMojoAnnotationsScanner.java:85)
	at org.apache.maven.tools.plugin.annotations.JavaAnnotationsMojoDescriptorExtractor.scanAnnotations(JavaAnnotationsMojoDescriptorExtractor.java:125)
	at org.apache.maven.tools.plugin.annotations.JavaAnnotationsMojoDescriptorExtractor.execute(JavaAnnotationsMojoDescriptorExtractor.java:104)
	at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:108)
	at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:233)
	at org.apache.maven.plugin.plugin.DescriptorGeneratorMojo.execute(DescriptorGeneratorMojo.java:82)

```

---

**Affects:** 3.1

**Issue Links:**
- [MPIR-142](https://issues.apache.org/jira/browse/MPIR-142) Dependency report fails to generate if dependencies contain com.ibm.icu:icu4j:2.6.1

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

as written in MPIR-142

> it's a known bug in icu4j 2.6: see [ticket #6505](http://icu-project.org/trac/ticket/6505), which shows the problem wihtout Maven or bcel but directly a JVM
> marked as fixed in icu4j 2.8: see [ticket #3209](http://icu-project.org/trac/ticket/3209)
