### ISSUE TITLE
[MPLUGIN-191] plugin-info.html is not created

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#887]
**[Balazs Zsoldos](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=balazs.zsoldos)** opened **[MPLUGIN-191](https://issues.apache.org/jira/browse/MPLUGIN-191?redirect=false)** and commented

During running maven-plugin-plugin:report the following exception occurs:

```
Caused by: java.lang.NoClassDefFoundError: org/apache/maven/doxia/module/xhtml/decoration/render/RenderingContext
	at org.apache.maven.reporting.sink.SinkFactory.createSink(SinkFactory.java:59)
	at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:85)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.doxia.module.xhtml.decoration.render.RenderingContext
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
	... 23 more
```

After some debugging it seams to me that the cause is the version of maven-reporting-impl dependency which is now 2.0.5. I made it work with the following snippet in my pom.xml:

```xml
<plugin>
     <groupId>org.apache.maven.plugins</groupId>
     <artifactId>maven-plugin-plugin</artifactId>
     <version>2.9</version>
     <executions>
              <execution>
                       <id>report</id>
                       <phase>pre-site</phase>
                       <goals>
                                <goal>report</goal>
                       </goals>
              </execution>
     </executions>
     <dependencies>
              <dependency>
                       <groupId>org.apache.maven.reporting</groupId>
                       <artifactId>maven-reporting-impl</artifactId>
                       <version>2.2</version>
              </dependency>
     </dependencies>
</plugin>
```

After this setting the plugin-info.html file is generated at target/generated-site/xdoc directory. However nothing is copied to target/site as the output file should be moved to target/generated-site/xhtml and it should have the extension .xhtml.vm.

I made the workaround that I copy and rename the html file to src/site/xhtml/plugin-info.xhtml.vm.

---

**Affects:** 2.9

**Issue Links:**
- [MPLUGIN-187](https://issues.apache.org/jira/browse/MPLUGIN-187) plugin:report fails with maven-plugin-plugin 2.9
 (_**"duplicates"**_)

3 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Andreas Horst](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ahorst)** commented

Reproduced the same problem and fix in our Maven plugin project.

**Comment by jira-importer** [comment]
**[Balazs Zsoldos](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=balazs.zsoldos)** commented

Half of the issue is solved. The plugin still generates plugin-info.html into targate/generated-site/xdoc although this file is not an xdoc but an xhtml.vm. Due to this reason the plugin-info.html is not in the finally generated site. Tested with the version 3.1.

**Comment by jira-importer** [comment]
**[badgers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=badgers)** commented

Just confirming the above behaviour seen by Balazs Zsoldos on 10/Oct/12. Testing on one of our plugins that is dependent on maven-plugin-plugin 3.2. Below is a snippet from our POM. The build is running on Maven 3.0.4.

```xml
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-plugin-plugin</artifactId>
          <version>3.2</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <artifactId>maven-plugin-plugin</artifactId>
        <configuration>
          <skipErrorNoDescriptorsFound>true</skipErrorNoDescriptorsFound>
        </configuration>
        <executions>
          <execution>
            <id>mojo-descriptor</id>
            <phase>process-classes</phase>
            <goals>
              <goal>descriptor</goal>
            </goals>
          </execution>
          <execution>
            <id>report</id>
            <phase>pre-site</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <reporting>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-plugin-plugin</artifactId>
        <version>3.2</version>
      </plugin>
    </plugins>
  </reporting>
```

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

closing as duplicate of MPLUGIN-187

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I just notices that the original issue was solved, but there's a related issue. Reopening...

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed in [r1588642](http://svn.apache.org/r1588642)
